version: '3.7'
services:
  api_rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest
    tty: true
    ports:
      - "8000:8000"
    links:
      - api_db
      - sonarqube
    volumes:
      - ../:/app
    networks:
      - app-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_HOST: api_db
  api_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api_database
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - app-network
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile_sonarqube
    container_name: sonarqube_api
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
networks:
  app-network:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  