version: '3.7'
services:
  api_rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest
    tty: true
    ports:
      - "8000:8000"
    links:
      - api_db
    volumes:
      - ..\:/app
    networks:
      - app-network
  api_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api_database
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - app-network
networks:
  app-network:
    driver: bridge